In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [7]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [8]:
arr[0:5] = 100

In [9]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [10]:
arr = np.arange(0,11)

In [12]:
slice_of_arr = arr[0:6]

In [13]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [14]:
slice_of_arr[:] = 99

In [15]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [16]:
arr # notice that slice_of_arr also changed the original array, because it is not a copy, it is a reference to arr. 

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [17]:
arr_copy = arr.copy()

In [18]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexing 2d arrays

In [21]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [22]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

## Double Bracket

In [26]:
arr_2d[2][1] # selects the row, then the index in that row

40

## Single Bracket

In [27]:
arr_2d[2,1] 

40

## Sub-matrices

In [30]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [29]:
arr_2d[:2,1:] # These are two slices 

array([[10, 15],
       [25, 30]])

In [35]:
arr_2d[1:3,1:]

array([[25, 30],
       [40, 45]])

## Conditional Selection

In [36]:
arr1 = np.arange(1,11)

In [37]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
arr1 > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [40]:
bool_array = arr1 > 5

In [41]:
arr1[bool_array]

array([ 6,  7,  8,  9, 10])

In [43]:
arr1[arr1<3]

array([1, 2])

In [44]:
arr_2d1 = np.arange(50).reshape(5,10) # This is just for practice taking slices

In [45]:
arr_2d1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [48]:
arr_2d1[1:4,4:8]

array([[14, 15, 16, 17],
       [24, 25, 26, 27],
       [34, 35, 36, 37]])