In [1]:
 my_list = [1,2,3]

In [2]:
import numpy as np

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [5]:
my_mat = [[1,2,3], [4,5,6], [7,8,9]]

In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Generating Numpy Arrays

In [9]:
np.arange(0,10,2) # 0 start, 10 stop, 2 step

array([0, 2, 4, 6, 8])

In [10]:
np.zeros(3) # one dimensional

array([0., 0., 0.])

In [12]:
np.zeros((5,5)) # Pass in a tuple, and get a 5 x 5

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.linspace(0,5,10) # 1 dimensional array, you can tell by the single bracket

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [15]:
np.eye(4) # Identity matrix must be square

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
np.random.rand(5,5) # Random numbers from a uniform distibution

array([[0.91188703, 0.06123509, 0.70213353, 0.69246879, 0.93819788],
       [0.15095938, 0.8987349 , 0.91141066, 0.42573071, 0.38543713],
       [0.59454861, 0.12217671, 0.17061129, 0.39247431, 0.24519773],
       [0.20901302, 0.68860316, 0.40217143, 0.12994605, 0.58843557],
       [0.39523318, 0.57503617, 0.70261895, 0.80999257, 0.27878201]])

In [18]:
np.random.randn(2,4)  # Standard distibution these numbers plotted out would should a normal/Guasian distribution curve

array([[ 0.08040119, -1.09389753,  0.71952958, -2.1738774 ],
       [ 0.92478906,  0.88443245,  0.74880683,  1.51332309]])

In [20]:
np.random.randint(1,101, 10) #inclusive on the low and end but exclusive on the high end

array([63, 86, 80, 25, 47, 94, 15, 19, 13, 87])

## useful attributes and methods of Arrays

In [21]:
arr = np.arange(25)

In [22]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
ranarr = np.random.randint(0,50,10)

In [24]:
ranarr

array([22, 35,  6, 30, 37, 37,  5, 34, 15, 15])

In [26]:
arr.reshape(5,5) # This can modify a single array into an array of x rows and x columns

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [29]:
ranarr.max() # you can also run min()

37

In [31]:
ranarr.argmax() # This will return the index location of the max value

4

In [32]:
arr.shape # Show shape of array

(25,)

In [33]:
arr = arr.reshape(5,5)

In [35]:
arr.shape

(5, 5)

In [36]:
arr.dtype

dtype('int32')

In [39]:
from numpy.random import randint #This can be useful for giving a nickname to a common method

In [38]:
randint(2,10)

6